#!/usr/bin/env bash

# Filename:      vim2html
# Description:   Convert source code to html using vim
# Maintainer:    Jeremy Cantrell <jmcantrell@gmail.com>
# Last Modified: Wed 2010-12-01 15:40:31 (-0500)

# Vim is really good at recognizing filetypes and highlighting the syntax in a
# myriad of colorschemes. Vim is also good at turning that highlighted code
# into HTML. The only missing piece was making this process parameter driven
# and scriptable. That's what this script is intended to solve.

# IMPORTS {{{1

source bashful-files
source bashful-input
source bashful-messages
source bashful-modes

# FUNCTIONS {{{1

let_value()
{
    [[ $2 ]] && echo "let $1=$2"
}

set_value()
{
    [[ $2 ]] && echo "set $1=$2"
}

set_boolean()
{
    [[ $2 ]] && echo "set $1"
}

colorscheme()
{
    [[ $1 ]] && echo "colorscheme $1"
}

set_folding()
{
    if [[ $FOLDING ]]; then
        set_value foldmethod marker
        let_value g:html_dynamic_folds 1
    fi
}

# VARIABLES {{{1

SCRIPT_NAME=$(basename "$0" .sh)
SCRIPT_ARGUMENTS="INPUT [OUTPUT]"
SCRIPT_USAGE="Convert source code to html using vim."
SCRIPT_OPTIONS="
-t FILETYPE       Use FILETYPE as vim filetype.
-c COLORSCHEME    Use COLORSCHEME as vim colorscheme.
-s TABSTOP        Use TABSTOP for vim tabstop.
-n                Output line numbers.
-f                Allow folds.
-l                Use light background.
-x                Ignore user configs.
-T                Use tidy to cleanup HTML.
"

interactive ${INTERACTIVE:-0}
verbose     ${VERBOSE:-0}

# COMMAND-LINE OPTIONS {{{1

unset OPTIND
while getopts ":hifvqf:nt:c:lTs:x" option; do
    case $option in
        t) FILETYPE=$OPTARG ;;
        c) COLORSCHEME=$OPTARG ;;
        s) TABSTOP=$OPTARG ;;
        n) NUMBERED=1 ;;
        f) FOLDING=1 ;;
        l) BACKGROUND=light ;;
        d) BACKGROUND=dark ;;
        T) TIDY=1 ;;
        x) NORC=1 ;;

        i) interactive 1 ;;
        f) interactive 0 ;;

        v) verbose 1 ;;
        q) verbose 0 ;;

        h) usage 0 ;;
        *) usage 1 ;;
    esac
done && shift $(($OPTIND - 1))

# ERROR CHECKING {{{1

INFILE=$1

if [[ ! $INFILE ]]; then
    die "Input file not provided."
fi

if [[ ! -f $INFILE ]]; then
    die "Input file does not exist or is not a regular file."
fi

OUTFILE=$2

if [[ ! $OUTFILE ]]; then
    OUTFILE=${INFILE##*/}.html
fi

if [[ -f $OUTFILE ]]; then
    question -c -p "Overwrite '$OUTFILE'?" || exit 1
fi

# BUILD CONVERSION SCRIPT {{{1

tempfile || exit 1

: >$TEMPFILE

cat >>$TEMPFILE<<-EOF
syntax on
set t_Co=256
set expandtabs
let g:html_use_css = 1
EOF

{
    set_value   tabstop    $TABSTOP
    set_value   background $BACKGROUND
    set_value   filetype   $FILETYPE
    set_boolean number     $NUMBERED

    colorscheme $COLORSCHEME

    set_folding

} >>$TEMPFILE

cat >>$TEMPFILE<<-EOF
TOhtml
w! $OUTFILE
qa!
EOF
#}}}

info -c "Converting file '$INFILE' to '$OUTFILE'..."

vim -n -N ${NORC:+-u NORC} -S "$TEMPFILE" "$INFILE" >/dev/null 2>&1

sed -i "s%<title>.*</title>%<title>$(basename "$INFILE")</title>%" "$OUTFILE"

if [[ $TIDY ]]; then
    info -c "Cleaning HTML file '$OUTFILE'..."
    tidy --tidy-mark no -utf8 -f /dev/null -clean -asxhtml -o "$OUTFILE" "$OUTFILE"
fi
